### ISSUE TITLE
French translation for Dash

### ISSUE THREAD

**Issue by brunobord** [fariapp/fari-games#61]
Hello there,

As far as I know, there's no French translation for Dash. And as I saw in #42, it's as open as "please make a PR". So, unless someone tells me that there's already one in progress, I'll start a French version... now!

**Comment by RPDeshaies** [comment]
Hey @brunobord! So no, there are no french translation for Dash right now, but if you do make one that would truly amazing! I could also upload it on itch and make a PDF for it.

**Comment by brunobord** [comment]
:+1:
