### ISSUE TITLE
Add licenses for the SRDs

### ISSUE THREAD

**Issue by craigmaloney** [fariapp/fari-games#7]
Please add details of the licenses for each of the SRDs listed: 

e.g.: for https://fari.games/en/srds/jasontocci/24xx adding the following license:

"Text by Jason Tocci under a Creative Commons Attribution 4.0 license (CC BY 4.0)"

would be helpful.

Thanks!

**Comment by RPDeshaies** [comment]
See #9 😄

**Comment by craigmaloney** [comment]
Excellent. Thank you!
